POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "LostBoysLeader",
  "name": "Peter Pan",
  "password": "ihatehook",
  "notes": [{ "content": "I wear green", "important": true }]
}