POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjJuZF91c2VybmFtZSIsImlkIjoiNjkwOTI2NDFiZjMxOWFlNzViYjIyYTI4IiwiaWF0IjoxNzYzMjAwOTM1fQ.9drI3u7iSJcWVoVDwMj3EDSF59y7uw5OKS695MSi5qQ

{
  "title": "10:33",
  "author": "author8",
  "url": "url8.0",
  "likes": 8,
  "userId": "69092641bf319ae75bb22a28"
}